insert into public.blog_posts (slug, title, description, content, author, status, published_at) values
(
  'self-hosting-proposal-software',
  'Why Self-Hosting Your Proposal Software Matters',
  'Data ownership, compliance, and full control — here''s why more teams are choosing self-hosted proposal tools.',
  E'## Your Proposals Contain Sensitive Data\n\nThink about what''s in your proposals: pricing strategies, profit margins, client budgets, internal processes, competitive advantages. This is some of the most sensitive business data you have — and it''s sitting on someone else''s servers.\n\nWith SaaS proposal tools, you''re trusting a third party with your most confidential business information. If they get breached, your data is exposed. If they shut down, your proposals disappear.\n\n## The Compliance Angle\n\nFor agencies working with enterprise clients, government contracts, or regulated industries (healthcare, finance, legal), data residency matters. Many contracts require that sensitive documents stay within specific geographic boundaries.\n\nSelf-hosting lets you:\n\n- **Choose your data center location** — EU, US, or anywhere your compliance requires\n- **Control access logs** — Full audit trail of who accessed what and when\n- **Meet SOC 2 requirements** — Your infrastructure, your security controls\n- **Satisfy client NDAs** — Prove that proposal data never leaves your environment\n\n## Performance and Reliability\n\nWhen your proposal tool is self-hosted, you control uptime. No more "Sorry, our vendor is having issues" when a client is trying to sign a $50K proposal at 11 PM on a Friday.\n\n## How Propsly Makes It Easy\n\nSelf-hosting doesn''t have to be painful. Propsly ships as a single Docker image:\n\n```bash\ndocker run -d -p 3000:3000 \\\n  -e DATABASE_URL=your_postgres_url \\\n  -e SUPABASE_URL=your_supabase_url \\\n  propsly/propsly:latest\n```\n\nThat''s it. Full proposal platform running on your infrastructure in under a minute.\n\n## The Best of Both Worlds\n\nNot ready to self-host? Use Propsly Cloud — we handle infrastructure, backups, and updates. Want to migrate later? Export everything and spin up your own instance. No lock-in, ever.\n\n## Your Data, Your Rules\n\nThe future of business software is open source and self-hostable. Your proposals are too important to trust to a black box.',
  'Propsly Team',
  'draft',
  null
),
(
  'proposal-tracking-psychology',
  'The Psychology of Proposal Tracking: When and How to Follow Up',
  'View tracking data reveals the best moments to follow up on proposals. Here''s what the data tells us.',
  E'## The Follow-Up Problem\n\nYou sent the proposal. Now what? Most people either follow up too soon (annoying) or too late (forgotten). The sweet spot is somewhere in between, and proposal tracking data can tell you exactly where.\n\n## What Tracking Data Reveals\n\nWhen you can see exactly when and how clients interact with your proposal, patterns emerge:\n\n- **First view within 1 hour** — High interest. They were waiting for it.\n- **Multiple views in 24 hours** — They''re sharing it internally. Decision is being discussed.\n- **Pricing section viewed 3+ times** — Price sensitivity. Consider offering options or payment terms.\n- **No view after 48 hours** — It''s buried in their inbox. Time for a gentle nudge.\n\n## The Golden Window\n\nThe best time to follow up is 2-4 hours after the client''s second view. Here''s why:\n\n- They''ve read it thoroughly (first view)\n- They''ve come back to review specific sections (second view)\n- They likely have questions but haven''t formulated them yet\n- Your proposal is top of mind\n\nA well-timed message like "I noticed you had a chance to review the proposal — happy to walk through any questions" feels helpful, not pushy.\n\n## Section-Level Insights\n\nPropsly tracks time spent on each section of your proposal. This tells you:\n\n- **Heavy time on scope** — They want to make sure deliverables are clear. Address this in your follow-up.\n- **Heavy time on pricing** — Budget concerns. Proactively offer flexibility.\n- **Heavy time on timeline** — Deadline pressure. Emphasize your ability to deliver on time.\n- **Skipped testimonials** — They already trust you. Don''t oversell.\n\n## The Re-Engagement Play\n\nSometimes proposals go cold. A client viewed it once, then nothing for a week. This is where smart tracking pays off.\n\nSet up notifications for "re-views" — when a cold prospect suddenly opens your proposal again. This often means:\n\n- Budget got approved\n- A competing vendor fell through\n- A new stakeholder is reviewing options\n\nThis is your moment. Follow up within the hour.\n\n## Don''t Be Creepy\n\nA word of caution: never reveal exactly what you know. "I see you spent 4 minutes on the pricing page" is unsettling. "I wanted to check if you had any questions about pricing or scope" is professional.\n\nUse tracking data to inform your approach, not to script your conversation.',
  'Propsly Team',
  'draft',
  null
);
